			writeSpeech("assistant", "", "Hey playerF, do you have a second?");
			writeTransition("katya1", "What's up?");

			writeSpeech("player", "", "What's up?");
			writeSpeech("assistant", "", "The other day I got a text from my sister, she's getting into college nearby");
			writeSpeech("player", "", "Nice!");
			writeSpeech("assistant", "", "Yeah it's great. It's just that I commute pretty far to get here, and she doesn't have a car, so...");
			writeSpeech("player", "", "We work for a shadowy corporation dealing in mystical artifacts. You can't just get her a driver?");
			writeSpeech("assistant", "", "I considered that, but since Mrs. bossL is in charge of the budget, I'd need to get her to sign off.");
			writeSpeech("player", "", "Ah. So you want me to...?");
			writeSpeech("assistant", "", "I was wondering if my sister could stay at your place, just for a little while until she gets her footing.");
			writeSpeech("player", "", "<i>Another woman living with me could be a pretty good target for some fun...</i>");
			writeTransition("katya1", "No problem");
			writeTransition("office", "I'll get back to you on that");

			writeSpeech("player", "", "I'll need to run it by roommateF first, but there shouldn't be a problem.");
			writeSpeech("assistant", "", "Yes! Thank you so much!");
			writeText("She gives you a big hug before pulling out her phone and calling her sister.");
			writeSpeech("assistant", "", "sisterF! Great news!");
			writeText("Likewise, you call up roommateF. She gives the okay for assistantF's sister to use the spare room.");

			//Bracelet 4
			writeText("As you disrobed to enjoy bossL with the bracelet's power, she suprised you by calling assistantF into her office. She started chewing out assistantF over something about report formatting.");
			writeText("You didn't pay too much attention to what she was saying.");
			writeBig("images/bracelet/research4-1.gif");
			writeSpeech("boss", "", "Do... Do I make myself clear, assistantL?");
			writeSpeech("assistant", "", "Yes ma'am! <br><i>Fuck, I screwed up on this one. She's red in the face... I wanna go home... </i>");
			writeText("You do feel a little bad for assistantF for a moment though, with the way you're pounding bossL's cunt, it looks like bossL is trying to get up in assistantF's face and intimidate her.");
			writeSpeech("player", "", "Acting so tough while you're getting fucked, you really do have an iron spirit, huh? How about... This!");
			writeBig("images/bracelet/research4-2.gif");
			writeSpeech("boss", "", "Ggghh~!");
			writeText("A hard spank causes bossL's cunt walls to suddenly clench around you.");
			writeSpeech("assistant", "", "<i>Did... Did she just have an orgasm from yelling at me? </i><br>I'll be... Be sure not to let it happen again, Mrs. bossL.");
			writeText("assistantF slowly eases her way out of the room as you push bossL's head down onto the desk, making sure she feels every inch of you.");
			writeSpeech("player", "", "Gonna cum, bitch! Take it all!");
			writeBig("images/bracelet/research4-3.gif");
			writeText("bossL's eyes roll back at her body shudders, but she doesn't make a sound as she tries to maintain her dignity.");

			//Bracelet 6
			writeText("The top floor, where the head honcho of Anomaly Vault spends her time. She's not super involved with most of the daily events, she's less CEO and more Majority Shareholder.");
			writeText("Rumors abound that she actually reports to a shadowy council, like the Illuminati but a cube, not a pyramid.");
			writeText("In any case it's no big deal to use the bracelet to sneak in. You slide past someone leaving and walk into her... Office?");
			writeBig("scripts/gamefiles/characters/chair,jpg");
			writeText("She looks right at you as the door closes, but she's probably just looking at the door behind you.");
			writeText("This place looks nothing like any office you've ever been in. There's no desk, and several walls give way to stunning balconies over large jungles. It's more like a botanical garden in here.");
			writeText("chairF chairL, the head of Anomaly Vault, takes a seat on a nearby chair. It doesn't seem like she notices you.");
			writeSpeech("player", "", "It's now or never.");
			writeText("...");
			writeBig("images/bracelet/research5-1.gif");
			writeText("You stripped off her fancy robes and got to work enjoying yourself with your new fleshlight. Her plump lips make good padding for your pelvis as you slam your cock down her throat.");
			writeText("Your hands are on her neck, enjoying the bulge your dick makes as you thrust in and out.");
			writeBig("images/bracelet/research5-2.gif");
			writeSpeech("player", "", "Gah! What the hell are you-");
			writeText("You jump in place as chairF grabs you by the ass to pull you deeper, taking you down to the balls. She moans as you feel her tongue slide out to run along your balls as she moans, clearly enjoying her prize.");
			writeSpeech("player", "", "F-fuck~<br>Can you see me?");
			writeText("She pulls back for a moment then slams her face down onto your crotch again.");
			writeSpeech("player", "", "God damn! Gonna cum!");
			writeText("This finally breaks her rhythm. She pulls herself off your dick, not even so much as a gag or *glch* and starts stroking your length.");
			writeSpeech("chair", "", "Do it. Give it to me.");
			writeBig("images/bracelet/research5-3.gif");
			writeText("She sighs appreciatively as your cock spurts its thick cream out onto her hand and arm.");
			writeText("You stumble back as you finish, chairF lewdly licks her fingers clean of your jizz.");
			writeSpeech("chair", "", "Well, I see you certainly enjoyed yourself. It was a lovely distraction for me as well.");
			writeSpeech("player", "", "How-?");
			writeSpeech("chair", "", "I am the chairwoman of the most powerful institution of the world. Even if I didn't have a bevy of reality-bending power sources in my possession, I still have ways to deal with perception alteration.");
			writeSpeech("player", "", "Oh.");
			writeSpeech("chair", "", "There's no need to worry. Neither your life or your job are in danger. If you were the type of person to use the bracelet for murder or something wasteful like that, we would have fried you the moment you touched it.");
			writeSpeech("player", "", "Do you mean 'fired'?");
			writeSpeech("chair", "", "No. <br>You should be getting back to work. The artifacts can get antsy when they feel ignored.");
			
			//bracelet home 4
			writeSpeech("sister", "", "What the fuck, you left the door open!");
			writeSpeech("Ashley", "none", "Huh...? I thought I closed it.");
			writeSpeech("Molly", "none", "Get your head in the game Ash, otherwise you're going to get destroyed tonight.");
			writeText(" You stand awkwardly in the corner as the girls filter into the living room and up the stairs. Slipping inside the room with the bracelet, you ware essentially invisible; Ashley didn't even notice as you followed right behind her. sisterF opens her bedroom door and the three teens pile onto the bed in front of the television.");
			writeBig("images/bracelet/katya1-1.gif");
			writeSpeech("Ashley", "none", "Aw, did you start playing already?");
			writeSpeech("Molly", "none", "Yup, I forgot to bring my controller so you're playing the winner.");
			writeText(" While the girls chit-chat, you salivate at the spread of teen pussy in front of you. For the past few years, you've watched your neighbor's daughter grow up to be a beautiful young woman... and it was time to reap the benefits!");
			writeSpeech("player", "", " Hey girls, mind if I help you get comfortable?");
			writeText(" It takes you no time at all to strip sisterF and her friends completely bottomless; the three of them are totally unaware of your presence even as their jeans slip off their shapely legs, revealing their shaved slits ripe for the taking.");
			writeBig("images/bracelet/katya1-2.gif");
			writeText(" You easily push your cock inside, enjoying the new sensation of sisterF's pussy...");
			writeSpeech("sister", "", "O-oh! Fu-fuck...");
			writeSpeech("Molly", "none", "What's up sisterF, you're really going to choke and let Ash play me next?");
			writeSpeech("sister", "", "Hah... n-not on your life!");
			writeBig("images/bracelet/katya1-3.gif");
			writeText(" After a few minutes of Heaven, you pull out and fuck another blissfully unaware teen...");
			writeSpeech("Molly", "none", "Ah! Uh, um, y-you scared me with that attack.");
			writeSpeech("Ashley", "none", "Yeah, right! Excuses, excuses, excuses.");
			writeBig("images/bracelet/katya1-4.gif");
			writeText(" Prodding their mouth, with a little effort you even get them tasting each other with your dick...");
			writeSpeech("Ashley", "none", "Mmmph... hmph!");
			writeSpeech("Molly", "none", "I can't believe you said that in class!");
			writeSpeech("sister", "", "Haha, yeah, that was pretty funny today.");
			writeSpeech("player", "", " Huh, now I want to know what she said...");
			writeBig("images/bracelet/katya1-5.gif");
			writeText(" By the time you round back to your neighbor's barely legal daughter, you only manage a few thrusts...");
			writeText(" ... before your throbbing cock slams inside her wet pussy and floods it with thick cum.");
			writeText(" After you pull out, the girls are still completely unaware, albeit out of breath and blushing red. The room reeks of hardcore sex and their bodies glisten with sweat, but they don't seem to mind. Their eyes are still glued to the TV as they play their game, even as sisterF's used pussy steadily oozes out your semen.");
			writeText(" In the end, they have a sleepover... and so do you.");

			//Midas coin research 2
			writeSpeech("player", "", "Hey, you gonna drink that?");
			writeSpeech("assistant", "", "Huh? Oh the soda. Yeah, and it's the last from the machine too, sorry.");
			writeSpeech("player", "", "Oh well. Hey, how about I buy it from you?");
			writeText("...");
			writeBig("images/coin/research2-1.gif");
			writeSpeech("assistant", "", "Glllch<br>Fuck, he's huge!");
			writeText("You grab assistantF by the hair and force her down farther. A shiver of pleasure travels up your back as you hear her let out a giggle while deepthroating you.");
			writeSpeech("player", "", "Fuck, how much are you enjoying this?");
			writeText("She doesn't answer with words, not that she can with her face skewered on your dick. Instead she just focuses on rubbing her pussy while trying to pleasure your dick as much as her mouth can.");
			writeSpeech("player", "", "Fuck, cumming~!");
			writeBig("images/coin/research2-2.gif");
			writeText("The room is filled even further with the sounds of a gag-fueled mouthfuck. assistantF doesn't let up even as you start to cum, you actually need to grab her by the hair and pull her off of you to get her to stop sucking, and even then she tries her best to suck down every drop.");
			writeSpeech("assistant", "", "He-*AHEM*<br>Mhmm... Sucker... The soda was only like two bucks...");
			writeText("She rests against the side of her desk as you start drinking the soda you 'paid' for.");

			//Midas coin home 3
			writeSpeech("player", "", "Hey sisterF, how's it going? Settling in fine?");
			writeSpeech("sister", "", "Yeah, I guess. Room's a bit small, but I'll manage. You need something?");
			writeSpeech("player", "", "Not really. Just wondering if you wanted some pocket money.");
			writeSpeech("sister", "", "Hell yeah I do! Thanks a-");
			writeText("sisterF lets out a yelp as you push her down onto the couch. She squeals in panic, looking like her life is flashing before her eyes.");
			writeSpeech("sister", "", "Wait stop! What the hell are you doing?");
			writeSpeech("player", "", "... Raping you?");
			writeSpeech("sister", "", "Oh! Oh man, I was stupid and got worried for a second. Sorry.");
			writeText("You ignore her little goof and get back to stripping her jeans off.");

			//Midas Coin 1 - Karlee and the Gold Membership 
			writeText("You fiddle with the coin, approaching Karlee at the counter.");
			writeSpeech("gym","","Oh, hey. It's "+data.player.fName+", right? I remember signing you up, but haven't seen you around.");
			writeSpeech("player","","That's me. I was actually planning on discussing those membership fees.");
			writeText("She gives a bit of a tired smile.");
			writeSpeech("gym","","Sorry, but company policy is that I can't give discounts after the fact, even if you haven't been around.");
			writeSpeech("player","","Actually, I'm here to pay them in advance, and maybe even upgrade?");
			writeText("She perks right up, smiling wide.");
			writeSpeech("gym","","In that case, we can talk in the back!");
			writeText("...");
			writeBig("images/coin/karleeCoin.gif");
			writeText("She tightens her ass every time you bottom out, trying not to moan.");
			writeSpeech("gym","","Y-You're not too bad! A l-little more, and you might pay for... for... F-Fuck...! <br> <i>C'mon Karlee, keep it together! You're a closer, not a quitter!</i>");
			writeSpeech("player","","For a personal trainer, aren't you a bit easily distracted?");
			writeSpeech("gym","","Not at all! I'm just... <i>very</i> focused on my client! <br> <i>Focus...! I'm so close to the sale I can practically feel it in my guts!</i>");
			writeText("You roll your hips while thrusting, feeling your head pressing into every fold.");
			writeSpeech("player","","Y'know, I'm just not sure if this is the right gym for me.");
			writeText("Panicking, she clamps down tight on your cock.");
			writeSpeech("gym","","I know this place'll be a <i>perfect fit</i> for you...!");
			writeText("You slap her ass harshly, Karlee moaning sharply as she keeps rythmically tensing up.");
			writeSpeech("gym","","W-We've got the best trainers around, and great equipment! No matter what kind of exercise you're looking for, you'll have people like me r-ready to c-<i>come</i> and help!");
			writeSpeech("player","","That's a pretty good offer, but... Don't you think you should give the price?");
			writeSpeech("gym","","Normally, it's another ten dollars a month, b-but I can make a one-time-deal! All of that, and all you've got to do is cum inside!");
			writeText("You can feel yourself approaching the edge, so might as well...");
			writeSpeech("player","","You've got a deal.");
			writeText("You ram your cock into her ass, the sound ringing out as she muffles a moan.");
			writeText("A few seconds later, you pour your load inside, a wave of relief going through her body.");
			writeBig("images/coin/karleeCoin2.gif");
			writeSpeech("gym","","T-Thank you for cumming...! You won't regret this...");
			writeSpeech("player","","I'm getting that feeling, yeah.");

			//Midas Coin 2
			writeText("In hindsight, it might not have been the most tactful option to go outside and scream, <i>\"We live in a free market economy\"</i> while undoing your belt, but on the other hand...");
			writeBig("images/coin/publicCoin.gif");
			writeText("At this point, you're more worried about undervaluing your currency...");
			writeSpeech("Tongue-Piercing Girl","none","Come on big guy! Shoot that hot, <i>thick</i> capitalism all over our proletariat faces~!");
			writeText("Wait what?");
			writeSpeech("Girl on the Right","none","Ignore her, she's just thirsty for your means of reproduction.");
			writeSpeech("player","","...Okay, so using an artifact that rewrites localized cognition has some unexpected effects. Live and learn.");
			writeText("Could be worse, though. First time you've had four tongues dancing across your cock...");
			writeSpeech("Nose-Piercing Girl","none","Are you getting close? Warn us before the money shot, okay hun?");
			writeText("Maybe it's a side-effect of working at the Vault, but you could swear the puns only turn you on more...");
			writeText("...");
			writeText("As fun as it is to be able to pay for snacks by going down on the cute cashier (and as much as you've learned to appreciate actual money when the cashier isn't your type), coming up with an interesting way of using the coin is... kinda hard.");
			writeText("Well, without having to resort to the Bracelet to keep yourself from getting a life-long ban from the store, anyway.");
			writeText("Standing in front of the door to your place, you eat some more of your sexually-attained snacks and think.");
			writeSpeech("player","","Can't believe I'm saying this, but I think I need some spare work...");
			writeSpeech("girlfriend","","What a coincidence.");
			writeText("You flinch, but keep yourself from jumping.");
			writeSpeech("player","","Hey girlfriendF. Pretty sure roommateF is working.");
			writeSpeech("girlfriend","","I was counting on it - I would like to ask you for a favor.");
			writeText("You slowly slide a chip into your maw.");
			writeSpeech("player","","Go on.");
			writeSpeech("girlfriend","","roommateF is... observant. Particularly when it comes to me, and <i>especially</i> regarding gifts.");
			writeSpeech("player","","Ah. Yeah, I think I see where this is going. You want my help picking something out?");
			writeSpeech("girlfriend","","Yes. I'd rather like my surprise to <i>surprise</i> her for once.");
			writeSpeech("player","","Not too hard. You know her favorite movies?");
			writeSpeech("girlfriend","","Casablanca?");
			writeSpeech("player","","Hah. I'm guessing she told you that on the first date? Her favorites are a little bit different...");
			writeText("...");
			writeText("With a pair Lord of the Rings bookends in tow, the two of you walk quietly to girlfriendF's place. When you get to the door...");
			writeSpeech("girlfriend","","I could've paid for that digitally, you know.");
			writeSpeech("player","","I figured, but why complicate things? You seem like the type to pay a guy back.");
			writeText("She pauses, then smiles.");
			writeSpeech("girlfriend","","Actually, you know what?");
			writeText("Her finger loops around your belt, pulling you with her into her house.");
			writeSpeech("girlfriend","","I think I'll do that now.");
			writeText("The door shuts as she deftly un-does your pants, pulling them down just enough to have your cock flop against her hand.");
			writeSpeech("girlfriend","","My throat for those bookends?");
			writeSpeech("player","","Sounds fair. Do you want to get warmed up, or-");
			writeText("She drops down, her mouth immediately getting to work.");
			writeSpeech("player","","Or not...!");
			writeText("...");
			writeBig("images/coin/asaCoin.gif");
			writeSpeech("player","","Holy <i>crap,</i> your throat is tight...!");
			writeText("She bobs down to the base for a moment before popping back up, one hand jerking your slick shaft.");
			writeSpeech("girlfriend","","If it weren't, it would hardly be worth the gift.");
			writeSpeech("player","","Fair point. You'd better be ready though...!");
			writeText("She smirks, throwing herself back into the blowjob enthusiastically.");
			writeText("Pretty soon, you buck your hips forward <i>hard</i>, bottoming out as you pump your cum down her throat.");
			writeText("When you finish, she pulls away and wipes a bit of cum and spit from her chin, licking it up with a smile.");
			writeSpeech("girlfriend","","Now we're even. Thanks for the help with the gift - I'm sure roommateF will love it.");

			//Coin dream
			writeText("A cold wind blows over the land, and you take a powerful breath of the show before you.");
			writeBig("images/coin/dream1-1.gif");
			writeText("More, more! You cry out. For all that it matters, society is your plaything.");
			writeText("You lean back to enjoy the ride, but a single slip causes something precious to roll from your fingers.");
			writeText("The coin rolls along the ground, stopping only for a crow to snatch it.");
			writeText("Around you, confused exclamations are followed by terrified screams.");
			writeText("Your paradise is lost to the ages.");

			//Serum research 2
			writeBig("images/serum/research2-1.gif");
			writeSpeech("assistant", "", "N-nggh... What's... It feels like something is wrong...");
			writeSpeech("player", "", "What could be wrong? This is pretty normal for us.");
			writeSpeech("assistant", "", "It is...? I don't remember.<br><i>Something about this feels... Off...</i>");
			writeSpeech("player", "", "Are you not enjoying yourself?");
			writeBig("images/serum/research2-2.gif");
			writeSpeech("assistant", "", "Mmm, no! This is great, but it just feels like something isn't quite right.<br>Like, mmm... Like my brain is saying something is wrong, and right at the same time, you know?");
			writeSpeech("player", "", "Nngh, gonna come. Want me to pull out?");
			writeSpeech("assistant", "", "No, inside me! Please!");
			writeBig("images/serum/research2-3.gif");
			writeSpeech("assistant", "", "Ah~ Feels good~<br><i>Whatever it is, it's probably not important.</i><br>Can we go again soon?");

			//Serum research 3
			writeSpeech("boss", "", "So, what was so important you needed to interrupt me?");
			writeText("You take a deep breath to compose yourself. The minty aftertaste of the serum does help you feel a little more empowered under her glare.");
			writeSpeech("player", "", "I know your secret. I know you're a complete buttslut who can't even make it through the day without fantasizing about my cock up your ass.<br>I know you can't hold back anymore, that you're at your breaking point.");
			writeText("After a moment of silence, bossF stands up, walks over to the door, shuts, and locks it.");
			writeText("And then immediately pulls you out of your chair by the tie.");
			writeSpeech("boss", "", "How'd you find out!? Who the fuck told you!? Was it chairL!?");
			writeSpeech("player", "", "Uh, n-");
			writeSpeech("boss", "", "Shove it!");
			writeText("She pushes you back onto your chair and opens a drawer on her desk..");
			writeSpeech("boss", "", "Trying to make me look bad in front of management, huh? Right before inspection, I bet. But you're right, I can't hold back.");
			writeText("She pulls something that looks pretty close to a gun out of her desk drawer.");
			writeSpeech("boss", "", "I'll need to throw you in a ditch somewhere afterwards, can't have this getting back to bite my perfect ass. Any last words?");
			writeSpeech("player", "", "Uh, I have a few actually! First, you aren't going to shoot! Next...");
			writeText("...");
			writeBig("images/serum/research2-1.gif");
			writeSpeech("boss", "", "Ah~! Ah~! Harder! Ruin me!");
			writeSpeech("player", "", "You fucking <b>BITCH</b>! Were you seriously about to kill me to get your rocks off!");
			writeSpeech("boss", "", "I'm sorry master~! I don't know what came over me, I just needed to be fucked so bad~! Punish me, please!");
			writeBig("images/serum/research2-2.gif");
			writeSpeech("boss", "", "Ah, yes~! More~!");
			writeSpeech("player", "", "Oh, you'll get more, slut.");

			//Serum dream
			writeText("Test tubes bubble around you. This dream feels a lot more recent than most.");
			writeBig("images/serum/dream1-1.gif");
			writeText("Cold metal keeps you clasped down as Mrs. chairL works your dick.");
			writeText("She mutters to herself, saying she almost has the 'final ingredient'.");
			writeText("The last piece of the puzzle before she has a serum powerful enough to take over Anomaly Vault and instate herself as head chairwoman.");

			//Toolkit 1
			writeText("You unclasp the locks on the toolkit. Inside are several different fliers, a large bottle of skin cream, a girl's sweater, and some yoga pants. The fliers get progressively more lewd, starting with women in fashionable outfits and ending with...");
			writeText("Something about this feels wrong, like you're skipping a step. Everything feels hazy as it feels like your body is on autopilot.");
			writeText("You disrobe yourself and squirt some of the cream onto your hand.");
			writeText("A faint part of your mind says to hold on, to figure out what is going on. Another, much louder part of your mind, probably scientific curiosity, pushes you forwards.");
			writeText("You rub the cream into your skin, it tingles. Everywhere it touches feels smooth. Once your finished your whole body is tingling and shivering and you fall over. How clumsy!");
			writeText("As you stand up and look back over yourself, your skin is now completely smooth and hairless. The fliers lay on the floor in a clump, you don't need them anymore.");
			writeText("<i>Still not finished.</i>");
			writeText("You put on the yoga pants and the sweater, they fit perfectly and relax on a nice soft bed.");
			writeBig("images/toolkit/research1-1.gif");
			writeText("You start stroking yourself, nice and slowly. You feel on edge already.");
			writeBig("images/toolkit/research1-2.gif");
			writeText("Already you're cumming, it feels so much thicker than normal. You can barely keep your hands on yourself, it feels like you could cum without touching your cock.");
			writeText("<i>Still not finished.</i>");
			writeText("You keep stroking and rubbing yourself, and you just keep cumming. Some part of you, deep inside, feels like it's getting bigger and stronger, while the rest of your body feels like it's getting weaker and softer.");
			writeBig("images/toolkit/research1-3.gif");
			writeText("<i>Good job.</i>");
			writeText("You snap to, coming out of your daze. You're you again.");
			writeText("You clean yourself off and switch back to our normal clothes. They feel... More loose.");

			//Toolkit 2
			writeText("You unclasp the locks on the toolkit. Inside are a bra, some panties, a few wigs, a soft-looking blouse, and a bottle of wine.");
			writeText("You don't feel the same impulsive autopilot you did before. Instead, looking at the contents of the kit, you feel like you're staring off the edge of a cliff. A voice in your mind screams. 'Jump!' 'Jump!'");
			writeText("So you do. You down the wine, it tastes fruity. Your skin tingles like it did before, and now everything around you is slightly blurry. The wine must be very fast acting.");
			writeText("You take the underwear out of the kit. You already have girly skin, it might be fun to see how it feels.");
			writeText("You slide on the bra and the panties, they feel really nice. Everything feels itchy for a moment, but you know better than to scratch! You take a seat on the bed and wait for it to pass, and it does.");
			writeBig("images/toolkit/research2-1.gif");
			writeText("Your cock looks so cute in the panties... And this bra makes your chest look big. Didn't you have a normal-looking chest before?");
			writeText("You rub your little cock through your panties. They're really nice, but it just doesn't feel... Right.");
			writeText("<i>Still not finished.</i>");
			writeText("And then the itching comes back, much stronger. It's so bad, and it doesn't go away! It's right below your navel, and pressing down on your tummy only makes it itch more!");
			writeText("Maybe something in the toolkit will help! You put on the blouse, nothing. You put on the wig, it makes you feel pretty, but now's not the time! You pull of the panties. The itching comes by in pulses, every time it crescendos it feels like you desperately need to masturbate.");
			writeText("You start trying to jerk yourself off, but it doesn't work. You can't get an erection with all this itching!");
			writeText("You try to drink more wine, but the bottle is empty! You press it to your lips, and you don't know why, but you start slobbering all over the bottle. How inappropriate! But, you're desperate, and with desperation comes ideas.");
			writeText("You set the bottle on the floor, it's really tough and solid, and squat over it.");
			writeText("You press your little butthole against the neck of the bottle, and it starts to slide into you. The itching is really bad, you can't hold back anymore!");
			writeText("And then the bottle bumps into something. Your body shivers, your little pecker jumps, and you can't hold back a sigh of relief. The itching finally weakens and you feel so... <i>Nice</i>...");
			writeText("<i>Still not finished.</i>");
			writeBig("images/toolkit/research2-2.gif");
			writeText("Whenever you start to lift yourself off the bottle, the itching comes back. But whenever you thrust yourself back down, the relief washes over you again.");
			writeText("You start going faster. Shallow thrusts, but the thing you're bumping into feels like it keeps getting bigger. The itching gets worse whenever it comes back, but the relief feels so good...");
			writeBig("images/toolkit/research2-3.gif");
			writeText("Part of you is aware that your pecker is squirting, but that doesn't matter. The itching, and the relief. That's all that's on your mind. You keep going, and your pecker keeps squirting. It's squirting alot! And just when it stops, it starts squirting again!");
			writeText("Your legs shake, you can't keep yourself up anymore. Eventually, you need to give up and fall backwards, and you push the bottle out of yourself.");
			writeText("<i>Good job.</i>");
			writeText("You snap to, coming out of your daze. You're you again.");
			writeText("Quickly you grab your pecker, it feels good to touch again, although a bit lacking in size compared to before.");
			writeText("You look undeniably feminine now, but you put your clothes back on and leave. It might be a bad idea to come back here.");

			//Toolkit 3
			writeText("With shaking hands you unclasp the locks on the toolkit, telling yourself this will be the last time. Inside is...");
			writeText("Nothing.");
			writeText("But there can't be nothing! You aren't done yet! You almost want to cry, until you feel a hand on your shoulder.");
			writeText("There's a man in the room with you, several in fact! They all look like they want to be your friend, and they all look... So...");
			writeText("They're all naked from the waist down, and all have real dicks. Much larger than yours. You can't help yourself, it's rude to do this without introducing yourself, but they don't seem to mind as you get on your knees.");
			writeBig("images/toolkit/research3-1.gif");
			writeText("You stroke the big, manly dick in front of you. Everyone is smiling, you must be doing it right! They have gifts, pretty lingerie, that must be why the toolbox was empty!");
			writeText("You put on some of the clothes, but the one in front of you seems sad that you stopped. The itching comes back again, and you let out a pretty giggle as you have an idea.");
			writeText("...");
			writeBig("images/toolkit/research3-2.gif");
			writeText("You can't help but squeal as he fucks you, as he pumps his big dick inside of you. There's no more itching, just the nice feeling of relief whenever he squishes your big bitch button with his dick.");
			writeText("You keep squirting onto the sheets! But you promise to lick it clean after, so they aren't mad.");
			writeText("Once the one inside you cums you feel the itching again, spreading throughout your body. But you feel like you can ignore it since it'll be satisfied again soon. All the other helpers want you to try on clothes too!");
			writeText("...");
			writeBig("images/toolkit/research3-3.gif");
			writeText("You're having a lot of fun with your new helpers. Some really mean lady keeps buzzing her voice in the room, but you have your helpers to protect you if she tries to punish you.");
			writeText("<i>Still not finished.</i>");
			writeText("Still not finished! It keeps repeating in your head. Will it ever say 'good job' again? You hope not.");
			writeText("BAD END");
			writeText("...");
			writeText("But there's a ray of hope. You can go on, and awaken from this bad dream, if you like.");